// <auto-generated />
using System;
using AIChatBot.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIChatBot.API.Migrations
{
    [DbContext(typeof(ChatBotDbContext))]
    [Migration("20260110231954_AddMistralDevstral")]
    partial class AddMistralDevstral
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AIChatBot.API.Models.Entities.AIModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferralSource")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AIModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Company = "Microsoft",
                            Description = "Phi-3 is a family of lightweight 3B (Mini) and 14B (Medium) state-of-the-art open models by Microsoft.",
                            LogoUrl = "assets/images/model-icons/phi.png",
                            ModelName = "phi3",
                            Name = "Phi-3 Mini",
                            ReferenceLink = "https://ollama.com/library/phi3:latest",
                            ReferralSource = "Ollama"
                        },
                        new
                        {
                            Id = 2,
                            Company = "Meta",
                            Description = "Meta Llama 3: The most capable openly available LLM to date.",
                            LogoUrl = "assets/images/model-icons/llama.png",
                            ModelName = "llama3",
                            Name = "LLaMA 3",
                            ReferenceLink = "https://ollama.com/library/llama3:latest",
                            ReferralSource = "Ollama"
                        },
                        new
                        {
                            Id = 3,
                            Company = "Mistral AI",
                            Description = "The 7B model released by Mistral AI, updated to version 0.3.",
                            LogoUrl = "assets/images/model-icons/mistralai.png",
                            ModelName = "mistral",
                            Name = "Mistral 7B",
                            ReferenceLink = "https://ollama.com/library/mistral:latest",
                            ReferralSource = "Ollama"
                        },
                        new
                        {
                            Id = 4,
                            Company = "Google",
                            Description = "Gemma is a family of lightweight, state-of-the-art open models built by Google DeepMind. Updated to version 1.1.",
                            LogoUrl = "assets/images/model-icons/gemma.png",
                            ModelName = "gemma:2b",
                            Name = "Gemma",
                            ReferenceLink = "https://ollama.com/library/gemma:2b",
                            ReferralSource = "Ollama"
                        },
                        new
                        {
                            Id = 5,
                            Company = "DeepSeek",
                            Description = "DeepSeek V3, a 685B-parameter, mixture-of-experts model, is the latest iteration of the flagship chat model family from the DeepSeek team.\nIt succeeds the DeepSeek V3 model and performs really well on a variety of tasks.",
                            LogoUrl = "assets/images/model-icons/deepseek.png",
                            ModelName = "deepseek/deepseek-chat-v3-0324:free",
                            Name = "DeepSeek v3",
                            ReferenceLink = "https://openrouter.ai/deepseek/deepseek-chat-v3-0324:free",
                            ReferralSource = "OpenRouter"
                        },
                        new
                        {
                            Id = 6,
                            Company = "Google",
                            Description = "Gemma 3 introduces multimodality, supporting vision-language input and text outputs. It handles context windows up to 128k tokens, understands over 140 languages, and offers improved math, reasoning, and chat capabilities, including structured outputs and function calling. Gemma 3 27B is Google's latest open source model, successor to Gemma 2.",
                            LogoUrl = "assets/images/model-icons/gemma.png",
                            ModelName = "google/gemma-3-27b-it:free",
                            Name = "Gemma 3 27B",
                            ReferenceLink = "https://openrouter.ai/google/gemma-3-27b-it:free",
                            ReferralSource = "OpenRouter"
                        },
                        new
                        {
                            Id = 7,
                            Company = "Google",
                            Description = "Gemini Flash 2.0 offers a significantly faster time to first token (TTFT) compared to Gemini Flash 1.5, while maintaining quality on par with larger models like Gemini Pro 1.5. It introduces notable enhancements in multimodal understanding, coding capabilities, complex instruction following, and function calling. These advancements come together to deliver more seamless and robust agentic experiences.",
                            LogoUrl = "assets/images/model-icons/gemini.png",
                            ModelName = "google/gemini-2.0-flash-exp:free",
                            Name = "Gemini Flash 2.0 - Limited",
                            ReferenceLink = "https://openrouter.ai/google/gemini-2.0-flash-exp:free",
                            ReferralSource = "OpenRouter"
                        },
                        new
                        {
                            Id = 8,
                            Company = "OpenAI",
                            Description = "GPT-3.5 Turbo is OpenAI's fastest model. It can understand and generate natural language or code, and is optimized for chat and traditional completion tasks.",
                            LogoUrl = "assets/images/model-icons/chatgpt.png",
                            ModelName = "openai/gpt-3.5-turbo-0613",
                            Name = "GPT-3.5 Turbo",
                            ReferenceLink = "https://openrouter.ai/openai/gpt-3.5-turbo-0613",
                            ReferralSource = "OpenRouter"
                        },
                        new
                        {
                            Id = 9,
                            Company = "Google",
                            Description = "Gemini Flash 2.0 offers a significantly faster time to first token (TTFT) compared to Gemini Flash 1.5, while maintaining quality on par with larger models like Gemini Pro 1.5. It introduces notable enhancements in multimodal understanding, coding capabilities, complex instruction following, and function calling. These advancements come together to deliver more seamless and robust agentic experiences.",
                            LogoUrl = "assets/images/model-icons/gemini.png",
                            ModelName = "google/gemini-2.0-flash-001",
                            Name = "Gemini Flash 2.0 - Unlimited",
                            ReferenceLink = "https://openrouter.ai/google/gemini-2.0-flash-001",
                            ReferralSource = "OpenRouter"
                        },
                        new
                        {
                            Id = 10,
                            Company = "Meta",
                            Description = "Llama 3.1 8B is a high-performance, lightweight model optimized for low latency and high throughput, hosted on Groq.",
                            LogoUrl = "assets/images/model-icons/llama.png",
                            ModelName = "llama-3.1-8b-instant",
                            Name = "LLaMA 3.1 8B (Groq)",
                            ReferenceLink = "https://console.groq.com/docs/models",
                            ReferralSource = "Groq"
                        },
                        new
                        {
                            Id = 11,
                            Company = "Mistral AI",
                            Description = "Devstral is a state-of-the-art model from Mistral AI, optimized for development tasks and now available for free via OpenRouter.",
                            LogoUrl = "assets/images/model-icons/mistralai.png",
                            ModelName = "mistralai/devstral-2512:free",
                            Name = "Mistral Devstral",
                            ReferenceLink = "https://openrouter.ai/mistralai/devstral-2512:free",
                            ReferralSource = "OpenRouter"
                        });
                });

            modelBuilder.Entity("AIChatBot.API.Models.Entities.AIModelChatMode", b =>
                {
                    b.Property<int>("AIModelId")
                        .HasColumnType("int");

                    b.Property<int>("ChatModeId")
                        .HasColumnType("int");

                    b.HasKey("AIModelId", "ChatModeId");

                    b.HasIndex("ChatModeId");

                    b.ToTable("AIModelChatModes");

                    b.HasData(
                        new
                        {
                            AIModelId = 1,
                            ChatModeId = 1
                        },
                        new
                        {
                            AIModelId = 1,
                            ChatModeId = 2
                        },
                        new
                        {
                            AIModelId = 2,
                            ChatModeId = 1
                        },
                        new
                        {
                            AIModelId = 2,
                            ChatModeId = 2
                        },
                        new
                        {
                            AIModelId = 3,
                            ChatModeId = 1
                        },
                        new
                        {
                            AIModelId = 3,
                            ChatModeId = 2
                        },
                        new
                        {
                            AIModelId = 4,
                            ChatModeId = 1
                        },
                        new
                        {
                            AIModelId = 4,
                            ChatModeId = 2
                        },
                        new
                        {
                            AIModelId = 5,
                            ChatModeId = 1
                        },
                        new
                        {
                            AIModelId = 5,
                            ChatModeId = 2
                        },
                        new
                        {
                            AIModelId = 6,
                            ChatModeId = 1
                        },
                        new
                        {
                            AIModelId = 6,
                            ChatModeId = 2
                        },
                        new
                        {
                            AIModelId = 7,
                            ChatModeId = 1
                        },
                        new
                        {
                            AIModelId = 7,
                            ChatModeId = 2
                        },
                        new
                        {
                            AIModelId = 8,
                            ChatModeId = 1
                        },
                        new
                        {
                            AIModelId = 8,
                            ChatModeId = 2
                        },
                        new
                        {
                            AIModelId = 8,
                            ChatModeId = 3
                        },
                        new
                        {
                            AIModelId = 8,
                            ChatModeId = 4
                        },
                        new
                        {
                            AIModelId = 9,
                            ChatModeId = 1
                        },
                        new
                        {
                            AIModelId = 9,
                            ChatModeId = 2
                        },
                        new
                        {
                            AIModelId = 9,
                            ChatModeId = 3
                        },
                        new
                        {
                            AIModelId = 9,
                            ChatModeId = 4
                        },
                        new
                        {
                            AIModelId = 10,
                            ChatModeId = 1
                        },
                        new
                        {
                            AIModelId = 10,
                            ChatModeId = 2
                        },
                        new
                        {
                            AIModelId = 11,
                            ChatModeId = 1
                        },
                        new
                        {
                            AIModelId = 11,
                            ChatModeId = 2
                        });
                });

            modelBuilder.Entity("AIChatBot.API.Models.Entities.AgentFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatSessionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DownloadUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChatSessionId");

                    b.HasIndex("UserId");

                    b.ToTable("AgentFiles");
                });

            modelBuilder.Entity("AIChatBot.API.Models.Entities.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatSessionId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChatSessionId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("AIChatBot.API.Models.Entities.ChatMode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChatModes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Mode = "chat",
                            Name = "Chat"
                        },
                        new
                        {
                            Id = 2,
                            Mode = "tools",
                            Name = "Tools"
                        },
                        new
                        {
                            Id = 3,
                            Mode = "agent",
                            Name = "Agent"
                        },
                        new
                        {
                            Id = 4,
                            Mode = "planner",
                            Name = "Agent with Planning"
                        },
                        new
                        {
                            Id = 5,
                            Mode = "rag",
                            Name = "Knowledge-Based (RAG)"
                        });
                });

            modelBuilder.Entity("AIChatBot.API.Models.Entities.ChatSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UniqueIdentity")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ChatSessions");
                });

            modelBuilder.Entity("AIChatBot.API.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AIChatBot.API.Models.Entities.AIModelChatMode", b =>
                {
                    b.HasOne("AIChatBot.API.Models.Entities.AIModel", "AIModel")
                        .WithMany("ChatModes")
                        .HasForeignKey("AIModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIChatBot.API.Models.Entities.ChatMode", "ChatMode")
                        .WithMany()
                        .HasForeignKey("ChatModeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AIModel");

                    b.Navigation("ChatMode");
                });

            modelBuilder.Entity("AIChatBot.API.Models.Entities.AgentFile", b =>
                {
                    b.HasOne("AIChatBot.API.Models.Entities.ChatSession", "ChatSession")
                        .WithMany()
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIChatBot.API.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIChatBot.API.Models.Entities.ChatMessage", b =>
                {
                    b.HasOne("AIChatBot.API.Models.Entities.ChatSession", null)
                        .WithMany("Messages")
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AIChatBot.API.Models.Entities.ChatSession", b =>
                {
                    b.HasOne("AIChatBot.API.Models.Entities.User", null)
                        .WithMany("ChatSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AIChatBot.API.Models.Entities.AIModel", b =>
                {
                    b.Navigation("ChatModes");
                });

            modelBuilder.Entity("AIChatBot.API.Models.Entities.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("AIChatBot.API.Models.Entities.User", b =>
                {
                    b.Navigation("ChatSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
